# Generated by Django 5.0.4 on 2024-05-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='age',
            new_name='year',
        ),
    ]
